- *True Ocean* - means the mission outcome was successfully landed to a specific region of the ocean

- *False Ocean* - means the mission outcome was unsuccessfully landed to a specific region of the ocean

- *True RTLS* - means the mission outcome was successfully landed to a ground pad

- *False RTLS* - means the mission outcome was unsuccessfully landed to a ground pad

- *True ASDS* - means the mission outcome was successfully landed on a drone ship

- *False ASDS* - means the mission outcome was unsuccessfully landed on a drone ship

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('dataset_part_1.csv')
df.head(10)

,rocket,payloads,launchpad,cores,date_utc,payload_mass,orbit,booster_version,launch_site,longitude,...,core_block,core_reused_count,core_serial,core_outcome,core_flights,core_gridfins,core_reused,core_legs,core_landing_pad,flight_number
0,5e9d0d95eda69973a809d1ec,5eb0e4b7b6c3bb0006eeb1e7,5e9e4501f509094ba4566f84,"{'core': '5e9e289ef359185f2b3b2628', 'flight':...",2010-06-04T18:45:00.000Z,6123.547647,LEO,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B0003,None None,1,False,False,False,NaN,1
1,5e9d0d95eda69973a809d1ec,5eb0e4bab6c3bb0006eeb1ea,5e9e4501f509094ba4566f84,"{'core': '5e9e289ef35918f39c3b262a', 'flight':...",2012-05-22T07:44:00.000Z,525.000000,LEO,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B0005,None None,1,False,False,False,NaN,2
2,5e9d0d95eda69973a809d1ec,5eb0e4bbb6c3bb0006eeb1ed,5e9e4501f509094ba4566f84,"{'core': '5e9e289ff3591884e03b262c', 'flight':...",2013-03-01T19:10:00.000Z,677.000000,ISS,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B0007,None None,1,False,False,False,NaN,3
3,5e9d0d95eda69973a809d1ec,5eb0e4bbb6c3bb0006eeb1ee,5e9e4502f509092b78566f87,"{'core': '5e9e289ff359180ae23b262d', 'flight':...",2013-09-29T16:00:00.000Z,500.000000,PO,Falcon 9,VAFB SLC 4E,-120.610829,...,1.0,0,B1003,False Ocean,1,False,False,False,NaN,4
4,5e9d0d95eda69973a809d1ec,5eb0e4bbb6c3bb0006eeb1ef,5e9e4501f509094ba4566f84,"{'core': '5e9e289ff35918862c3b262e', 'flight':...",2013-12-03T22:41:00.000Z,3170.000000,GTO,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B1004,None None,1,False,False,False,NaN,5
5,5e9d0d95eda69973a809d1ec,5eb0e4bbb6c3bb0006eeb1f0,5e9e4501f509094ba4566f84,"{'core': '5e9e289ff3591878603b262f', 'flight':...",2014-01-06T18:06:00.000Z,3325.000000,GTO,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B1005,None None,1,False,False,False,NaN,6
6,5e9d0d95eda69973a809d1ec,5eb0e4bbb6c3bb0006eeb1f1,5e9e4501f509094ba4566f84,"{'core': '5e9e289ff3591829343b2630', 'flight':...",2014-04-18T19:25:00.000Z,2296.000000,ISS,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B1006,True Ocean,1,False,False,True,NaN,7
7,5e9d0d95eda69973a809d1ec,5eb0e4bcb6c3bb0006eeb1f2,5e9e4501f509094ba4566f84,"{'core': '5e9e28a0f3591870a63b2631', 'flight':...",2014-07-14T15:15:00.000Z,1316.000000,LEO,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B1007,True Ocean,1,False,False,True,NaN,8
8,5e9d0d95eda69973a809d1ec,5eb0e4bcb6c3bb0006eeb1f3,5e9e4501f509094ba4566f84,"{'core': '5e9e28a0f359186e2e3b2632', 'flight':...",2014-08-05T08:00:00.000Z,4535.000000,GTO,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B1008,None None,1,False,False,False,NaN,9
9,5e9d0d95eda69973a809d1ec,5eb0e4bcb6c3bb0006eeb1f4,5e9e4501f509094ba4566f84,"{'core': '5e9e28a0f35918b1bc3b2633', 'flight':...",2014-09-07T05:00:00.000Z,4428.000000,GTO,Falcon 9,CCSFS SLC 40,-80.577366,...,1.0,0,B1011,None None,1,False,False,False,NaN,10

In [ ]:
df.isnull().sum()/df.shape[0]*100

rocket                0.000000
payloads              0.000000
launchpad             0.000000
cores                 0.000000
date_utc              0.000000
payload_mass          0.000000
orbit                 0.000000
booster_version       0.000000
launch_site           0.000000
longitude             0.000000
latitude              0.000000
core_block            0.000000
core_reused_count     0.000000
core_serial           0.000000
core_outcome          0.000000
core_flights          0.000000
core_gridfins         0.000000
core_reused           0.000000
core_legs             0.000000
core_landing_pad     28.888889
flight_number         0.000000
dtype: float64

#Calculate the number of launches on each site

In [ ]:
df['launch_site'].unique()

array(['CCSFS SLC 40', 'VAFB SLC 4E', 'KSC LC 39A'], dtype=object)

In [ ]:
for site in df['launch_site'].unique():
    print(site, df[df['launch_site']==site].shape[0])

CCSFS SLC 40 55
VAFB SLC 4E 13
KSC LC 39A 22

#Calculate the number and occurrence of each orbit

In [ ]:
df['orbit'].unique()

array(['LEO', 'ISS', 'PO', 'GTO', 'ES-L1', 'SSO', 'HEO', 'MEO', 'VLEO',
       'SO', 'GEO'], dtype=object)

In [ ]:
# Count the number of occurrences for each unique orbit
orbit_counts = df['orbit'].value_counts()

# Display the results
print(orbit_counts)

orbit
GTO      27
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
ES-L1     1
HEO       1
SO        1
GEO       1
Name: count, dtype: int64

In [ ]:
landing_outcomes = df['core_outcome'].value_counts()
print(landing_outcomes)

core_outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

In [ ]:
for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

0 True ASDS
1 None None
2 True RTLS
3 False ASDS
4 True Ocean
5 False Ocean
6 None ASDS
7 False RTLS

In [ ]:
bad_outcomes = set(landing_outcomes.keys()[[1, 3, 5, 6, 7]])
bad_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

#Create a landing outcome label from Outcome column

In [ ]:
df['landing_class'] = df['core_outcome'].apply(lambda x: 0 if x in bad_outcomes else 1)

In [ ]:
df['landing_class']

0     0
1     0
2     0
3     0
4     0
     ..
85    1
86    1
87    1
88    1
89    1
Name: landing_class, Length: 90, dtype: int64

In [ ]:
df['landing_class'].mean()

0.6666666666666666

In [ ]:
df

,rocket,payloads,launchpad,cores,date_utc,payload_mass,orbit,booster_version,launch_site,longitude,...,core_reused_count,core_serial,core_outcome,core_flights,core_gridfins,core_reused,core_legs,core_landing_pad,flight_number,landing_class
0,5e9d0d95eda69973a809d1ec,5eb0e4b7b6c3bb0006eeb1e7,5e9e4501f509094ba4566f84,"{'core': '5e9e289ef359185f2b3b2628', 'flight':...",2010-06-04T18:45:00.000Z,6123.547647,LEO,Falcon 9,CCSFS SLC 40,-80.577366,...,0,B0003,None None,1,False,False,False,NaN,1,0
1,5e9d0d95eda69973a809d1ec,5eb0e4bab6c3bb0006eeb1ea,5e9e4501f509094ba4566f84,"{'core': '5e9e289ef35918f39c3b262a', 'flight':...",2012-05-22T07:44:00.000Z,525.000000,LEO,Falcon 9,CCSFS SLC 40,-80.577366,...,0,B0005,None None,1,False,False,False,NaN,2,0
2,5e9d0d95eda69973a809d1ec,5eb0e4bbb6c3bb0006eeb1ed,5e9e4501f509094ba4566f84,"{'core': '5e9e289ff3591884e03b262c', 'flight':...",2013-03-01T19:10:00.000Z,677.000000,ISS,Falcon 9,CCSFS SLC 40,-80.577366,...,0,B0007,None None,1,False,False,False,NaN,3,0
3,5e9d0d95eda69973a809d1ec,5eb0e4bbb6c3bb0006eeb1ee,5e9e4502f509092b78566f87,"{'core': '5e9e289ff359180ae23b262d', 'flight':...",2013-09-29T16:00:00.000Z,500.000000,PO,Falcon 9,VAFB SLC 4E,-120.610829,...,0,B1003,False Ocean,1,False,False,False,NaN,4,0
4,5e9d0d95eda69973a809d1ec,5eb0e4bbb6c3bb0006eeb1ef,5e9e4501f509094ba4566f84,"{'core': '5e9e289ff35918862c3b262e', 'flight':...",2013-12-03T22:41:00.000Z,3170.000000,GTO,Falcon 9,CCSFS SLC 40,-80.577366,...,0,B1004,None None,1,False,False,False,NaN,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,5e9d0d95eda69973a809d1ec,5ef6a4600059c33cee4a829e,5e9e4502f509094188566f88,"{'core': '5ef670f10059c33cee4a826c', 'flight':...",2020-09-03T12:46:00.000Z,15600.000000,VLEO,Falcon 9,KSC LC 39A,-80.603956,...,12,B1060,True ASDS,2,True,True,True,5e9e3032383ecb6bb234e7ca,86,1
86,5e9d0d95eda69973a809d1ec,5ef6a48e0059c33cee4a829f,5e9e4502f509094188566f88,"{'core': '5e9e28a7f3591817f23b2663', 'flight':...",2020-10-06T11:29:00.000Z,15600.000000,VLEO,Falcon 9,KSC LC 39A,-80.603956,...,13,B1058,True ASDS,3,True,True,True,5e9e3032383ecb6bb234e7ca,87,1
87,5e9d0d95eda69973a809d1ec,5ef6a4d50059c33cee4a82a1,5e9e4502f509094188566f88,"{'core': '5e9e28a6f35918c0803b265c', 'flight':...",2020-10-18T12:25:00.000Z,15600.000000,VLEO,Falcon 9,KSC LC 39A,-80.603956,...,12,B1051,True ASDS,6,True,True,True,5e9e3032383ecb6bb234e7ca,88,1
88,5e9d0d95eda69973a809d1ec,5ef6a4ea0059c33cee4a82a2,5e9e4501f509094ba4566f84,"{'core': '5ef670f10059c33cee4a826c', 'flight':...",2020-10-24T15:31:00.000Z,15600.000000,VLEO,Falcon 9,CCSFS SLC 40,-80.577366,...,12,B1060,True ASDS,3,True,True,True,5e9e3033383ecbb9e534e7cc,89,1
89,5e9d0d95eda69973a809d1ec,5eb0e4d2b6c3bb0006eeb25e,5e9e4501f509094ba4566f84,"{'core': '5f57c5440622a633027900a0', 'flight':...",2020-11-05T23:24:00.000Z,3681.000000,MEO,Falcon 9,CCSFS SLC 40,-80.577366,...,8,B1062,True ASDS,1,True,False,True,5e9e3032383ecb6bb234e7ca,90,1

In [ ]:
df.to_csv("dataset_part_2.csv", index=False)